[package]
name = "fuzz-dancelight-fuzz"
edition = "2024"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.fuzz-dancelight]
path = ".."
